<?php

define('XSTREAMER_MODULE_DIR','xstreamer');
define('XSTREAMER_MODULE_ID','xStreamer'); //DO NOT CHANGE THIS
define('XSTREAMER_BASE_PATH', XOOPS_ROOT_PATH.'/modules/'.XSTREAMER_MODULE_DIR);
define('XSTREAMER_BASE_URL', XOOPS_URL.'/modules/'.XSTREAMER_MODULE_DIR);
define('XSTREAMER_CLASS_PATH', XSTREAMER_BASE_PATH.'/class');
define('XSTREAMER_ADMIN_PATH', XSTREAMER_BASE_PATH.'/admin');
define('XSTREAMER',XOOPS_URL.'/modules/'.XSTREAMER_MODULE_DIR);

?>
